apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: brightlazarus/udagram-api-feed:v2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: udagram-env
            - secretRef:
                name: mysecret
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: aws-cred
      volumes:
        - name: aws-cred
          configMap:
            name: aws-cred
