# CircleCI configuration file
version: 4

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
        - docker-compose -f docker-compose-build.yaml build --parallel